/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPost200ResponseUser
 */
export interface AuthLoginPost200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost200ResponseUser
     */
    profilePictureUrl: string | null;
}

/**
 * Check if a given object implements the AuthLoginPost200ResponseUser interface.
 */
export function instanceOfAuthLoginPost200ResponseUser(value: object): value is AuthLoginPost200ResponseUser {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('profilePictureUrl' in value) || value['profilePictureUrl'] === undefined) return false;
    return true;
}

export function AuthLoginPost200ResponseUserFromJSON(json: any): AuthLoginPost200ResponseUser {
    return AuthLoginPost200ResponseUserFromJSONTyped(json, false);
}

export function AuthLoginPost200ResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost200ResponseUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
        'profilePictureUrl': json['profilePictureUrl'],
    };
}

export function AuthLoginPost200ResponseUserToJSON(json: any): AuthLoginPost200ResponseUser {
    return AuthLoginPost200ResponseUserToJSONTyped(json, false);
}

export function AuthLoginPost200ResponseUserToJSONTyped(value?: AuthLoginPost200ResponseUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
        'profilePictureUrl': value['profilePictureUrl'],
    };
}

