/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSignupPostRequest
 */
export interface AuthSignupPostRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AuthSignupPostRequest
     */
    name: string;
}

/**
 * Check if a given object implements the AuthSignupPostRequest interface.
 */
export function instanceOfAuthSignupPostRequest(value: object): value is AuthSignupPostRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AuthSignupPostRequestFromJSON(json: any): AuthSignupPostRequest {
    return AuthSignupPostRequestFromJSONTyped(json, false);
}

export function AuthSignupPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignupPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'name': json['name'],
    };
}

export function AuthSignupPostRequestToJSON(json: any): AuthSignupPostRequest {
    return AuthSignupPostRequestToJSONTyped(json, false);
}

export function AuthSignupPostRequestToJSONTyped(value?: AuthSignupPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'name': value['name'],
    };
}

