/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSignupPost200Response
 */
export interface AuthSignupPost200Response {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupPost200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the AuthSignupPost200Response interface.
 */
export function instanceOfAuthSignupPost200Response(value: object): value is AuthSignupPost200Response {
    return true;
}

export function AuthSignupPost200ResponseFromJSON(json: any): AuthSignupPost200Response {
    return AuthSignupPost200ResponseFromJSONTyped(json, false);
}

export function AuthSignupPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignupPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AuthSignupPost200ResponseToJSON(json: any): AuthSignupPost200Response {
    return AuthSignupPost200ResponseToJSONTyped(json, false);
}

export function AuthSignupPost200ResponseToJSONTyped(value?: AuthSignupPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

