/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthSignupPost500Response
 */
export interface AuthSignupPost500Response {
    /**
     * 
     * @type {string}
     * @memberof AuthSignupPost500Response
     */
    error?: string;
}

/**
 * Check if a given object implements the AuthSignupPost500Response interface.
 */
export function instanceOfAuthSignupPost500Response(value: object): value is AuthSignupPost500Response {
    return true;
}

export function AuthSignupPost500ResponseFromJSON(json: any): AuthSignupPost500Response {
    return AuthSignupPost500ResponseFromJSONTyped(json, false);
}

export function AuthSignupPost500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthSignupPost500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AuthSignupPost500ResponseToJSON(json: any): AuthSignupPost500Response {
    return AuthSignupPost500ResponseToJSONTyped(json, false);
}

export function AuthSignupPost500ResponseToJSONTyped(value?: AuthSignupPost500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

