/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserUserIdDelete200Response
 */
export interface AuthUserUserIdDelete200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthUserUserIdDelete200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the AuthUserUserIdDelete200Response interface.
 */
export function instanceOfAuthUserUserIdDelete200Response(value: object): value is AuthUserUserIdDelete200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AuthUserUserIdDelete200ResponseFromJSON(json: any): AuthUserUserIdDelete200Response {
    return AuthUserUserIdDelete200ResponseFromJSONTyped(json, false);
}

export function AuthUserUserIdDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserUserIdDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function AuthUserUserIdDelete200ResponseToJSON(json: any): AuthUserUserIdDelete200Response {
    return AuthUserUserIdDelete200ResponseToJSONTyped(json, false);
}

export function AuthUserUserIdDelete200ResponseToJSONTyped(value?: AuthUserUserIdDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

