/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadTranscodeVideoPostRequest
 */
export interface UploadTranscodeVideoPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UploadTranscodeVideoPostRequest
     */
    videoID: string;
}

/**
 * Check if a given object implements the UploadTranscodeVideoPostRequest interface.
 */
export function instanceOfUploadTranscodeVideoPostRequest(value: object): value is UploadTranscodeVideoPostRequest {
    if (!('videoID' in value) || value['videoID'] === undefined) return false;
    return true;
}

export function UploadTranscodeVideoPostRequestFromJSON(json: any): UploadTranscodeVideoPostRequest {
    return UploadTranscodeVideoPostRequestFromJSONTyped(json, false);
}

export function UploadTranscodeVideoPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadTranscodeVideoPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'videoID': json['videoID'],
    };
}

export function UploadTranscodeVideoPostRequestToJSON(json: any): UploadTranscodeVideoPostRequest {
    return UploadTranscodeVideoPostRequestToJSONTyped(json, false);
}

export function UploadTranscodeVideoPostRequestToJSONTyped(value?: UploadTranscodeVideoPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoID': value['videoID'],
    };
}

