/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadTranscodeVideoPost200Response
 */
export interface UploadTranscodeVideoPost200Response {
    /**
     * 
     * @type {string}
     * @memberof UploadTranscodeVideoPost200Response
     */
    success: string;
}

/**
 * Check if a given object implements the UploadTranscodeVideoPost200Response interface.
 */
export function instanceOfUploadTranscodeVideoPost200Response(value: object): value is UploadTranscodeVideoPost200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UploadTranscodeVideoPost200ResponseFromJSON(json: any): UploadTranscodeVideoPost200Response {
    return UploadTranscodeVideoPost200ResponseFromJSONTyped(json, false);
}

export function UploadTranscodeVideoPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadTranscodeVideoPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UploadTranscodeVideoPost200ResponseToJSON(json: any): UploadTranscodeVideoPost200Response {
    return UploadTranscodeVideoPost200ResponseToJSONTyped(json, false);
}

export function UploadTranscodeVideoPost200ResponseToJSONTyped(value?: UploadTranscodeVideoPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

