/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPutRequest
 */
export interface UserPutRequest {
    /**
     * 
     * @type {string}
     * @memberof UserPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPutRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the UserPutRequest interface.
 */
export function instanceOfUserPutRequest(value: object): value is UserPutRequest {
    return true;
}

export function UserPutRequestFromJSON(json: any): UserPutRequest {
    return UserPutRequestFromJSONTyped(json, false);
}

export function UserPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserPutRequestToJSON(json: any): UserPutRequest {
    return UserPutRequestToJSONTyped(json, false);
}

export function UserPutRequestToJSONTyped(value?: UserPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'password': value['password'],
    };
}

