/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDelete200Response
 */
export interface UserDelete200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UserDelete200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the UserDelete200Response interface.
 */
export function instanceOfUserDelete200Response(value: object): value is UserDelete200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UserDelete200ResponseFromJSON(json: any): UserDelete200Response {
    return UserDelete200ResponseFromJSONTyped(json, false);
}

export function UserDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UserDelete200ResponseToJSON(json: any): UserDelete200Response {
    return UserDelete200ResponseToJSONTyped(json, false);
}

export function UserDelete200ResponseToJSONTyped(value?: UserDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

