/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdatePutRequest
 */
export interface UserUpdatePutRequest {
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdatePutRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the UserUpdatePutRequest interface.
 */
export function instanceOfUserUpdatePutRequest(value: object): value is UserUpdatePutRequest {
    return true;
}

export function UserUpdatePutRequestFromJSON(json: any): UserUpdatePutRequest {
    return UserUpdatePutRequestFromJSONTyped(json, false);
}

export function UserUpdatePutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function UserUpdatePutRequestToJSON(json: any): UserUpdatePutRequest {
    return UserUpdatePutRequestToJSONTyped(json, false);
}

export function UserUpdatePutRequestToJSONTyped(value?: UserUpdatePutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'password': value['password'],
    };
}

