/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUserIdSubscribeGet200Response
 */
export interface UserUserIdSubscribeGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UserUserIdSubscribeGet200Response
     */
    subscriptionStatus: boolean;
}

/**
 * Check if a given object implements the UserUserIdSubscribeGet200Response interface.
 */
export function instanceOfUserUserIdSubscribeGet200Response(value: object): value is UserUserIdSubscribeGet200Response {
    if (!('subscriptionStatus' in value) || value['subscriptionStatus'] === undefined) return false;
    return true;
}

export function UserUserIdSubscribeGet200ResponseFromJSON(json: any): UserUserIdSubscribeGet200Response {
    return UserUserIdSubscribeGet200ResponseFromJSONTyped(json, false);
}

export function UserUserIdSubscribeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUserIdSubscribeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionStatus': json['subscriptionStatus'],
    };
}

export function UserUserIdSubscribeGet200ResponseToJSON(json: any): UserUserIdSubscribeGet200Response {
    return UserUserIdSubscribeGet200ResponseToJSONTyped(json, false);
}

export function UserUserIdSubscribeGet200ResponseToJSONTyped(value?: UserUserIdSubscribeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionStatus': value['subscriptionStatus'],
    };
}

