/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserGetIDGet200Response
 */
export interface UserGetIDGet200Response {
    /**
     * 
     * @type {string}
     * @memberof UserGetIDGet200Response
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UserGetIDGet200Response
     */
    name: string;
}

/**
 * Check if a given object implements the UserGetIDGet200Response interface.
 */
export function instanceOfUserGetIDGet200Response(value: object): value is UserGetIDGet200Response {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UserGetIDGet200ResponseFromJSON(json: any): UserGetIDGet200Response {
    return UserGetIDGet200ResponseFromJSONTyped(json, false);
}

export function UserGetIDGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGetIDGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'name': json['name'],
    };
}

export function UserGetIDGet200ResponseToJSON(json: any): UserGetIDGet200Response {
    return UserGetIDGet200ResponseToJSONTyped(json, false);
}

export function UserGetIDGet200ResponseToJSONTyped(value?: UserGetIDGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'name': value['name'],
    };
}

