/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserUpdatePut200Response
 */
export interface UserUpdatePut200Response {
    /**
     * 
     * @type {boolean}
     * @memberof UserUpdatePut200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the UserUpdatePut200Response interface.
 */
export function instanceOfUserUpdatePut200Response(value: object): value is UserUpdatePut200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UserUpdatePut200ResponseFromJSON(json: any): UserUpdatePut200Response {
    return UserUpdatePut200ResponseFromJSONTyped(json, false);
}

export function UserUpdatePut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdatePut200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function UserUpdatePut200ResponseToJSON(json: any): UserUpdatePut200Response {
    return UserUpdatePut200ResponseToJSONTyped(json, false);
}

export function UserUpdatePut200ResponseToJSONTyped(value?: UserUpdatePut200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

