/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoAllVideosGet200ResponseInner
 */
export interface VideoAllVideosGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof VideoAllVideosGet200ResponseInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof VideoAllVideosGet200ResponseInner
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof VideoAllVideosGet200ResponseInner
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof VideoAllVideosGet200ResponseInner
     */
    uploadDate: number;
    /**
     * 
     * @type {string}
     * @memberof VideoAllVideosGet200ResponseInner
     */
    status: string;
}

/**
 * Check if a given object implements the VideoAllVideosGet200ResponseInner interface.
 */
export function instanceOfVideoAllVideosGet200ResponseInner(value: object): value is VideoAllVideosGet200ResponseInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('uploadDate' in value) || value['uploadDate'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function VideoAllVideosGet200ResponseInnerFromJSON(json: any): VideoAllVideosGet200ResponseInner {
    return VideoAllVideosGet200ResponseInnerFromJSONTyped(json, false);
}

export function VideoAllVideosGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoAllVideosGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'title': json['title'],
        'uploadDate': json['uploadDate'],
        'status': json['status'],
    };
}

export function VideoAllVideosGet200ResponseInnerToJSON(json: any): VideoAllVideosGet200ResponseInner {
    return VideoAllVideosGet200ResponseInnerToJSONTyped(json, false);
}

export function VideoAllVideosGet200ResponseInnerToJSONTyped(value?: VideoAllVideosGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'title': value['title'],
        'uploadDate': value['uploadDate'],
        'status': value['status'],
    };
}

