/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdLikePost200Response
 */
export interface VideoVideoIdLikePost200Response {
    /**
     * 
     * @type {number}
     * @memberof VideoVideoIdLikePost200Response
     */
    likes: number;
}

/**
 * Check if a given object implements the VideoVideoIdLikePost200Response interface.
 */
export function instanceOfVideoVideoIdLikePost200Response(value: object): value is VideoVideoIdLikePost200Response {
    if (!('likes' in value) || value['likes'] === undefined) return false;
    return true;
}

export function VideoVideoIdLikePost200ResponseFromJSON(json: any): VideoVideoIdLikePost200Response {
    return VideoVideoIdLikePost200ResponseFromJSONTyped(json, false);
}

export function VideoVideoIdLikePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdLikePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'likes': json['likes'],
    };
}

export function VideoVideoIdLikePost200ResponseToJSON(json: any): VideoVideoIdLikePost200Response {
    return VideoVideoIdLikePost200ResponseToJSONTyped(json, false);
}

export function VideoVideoIdLikePost200ResponseToJSONTyped(value?: VideoVideoIdLikePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'likes': value['likes'],
    };
}

