/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdGet200ResponseCommentsInner
 */
export interface VideoVideoIdGet200ResponseCommentsInner {
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdGet200ResponseCommentsInner
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdGet200ResponseCommentsInner
     */
    text: string;
}

/**
 * Check if a given object implements the VideoVideoIdGet200ResponseCommentsInner interface.
 */
export function instanceOfVideoVideoIdGet200ResponseCommentsInner(value: object): value is VideoVideoIdGet200ResponseCommentsInner {
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function VideoVideoIdGet200ResponseCommentsInnerFromJSON(json: any): VideoVideoIdGet200ResponseCommentsInner {
    return VideoVideoIdGet200ResponseCommentsInnerFromJSONTyped(json, false);
}

export function VideoVideoIdGet200ResponseCommentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdGet200ResponseCommentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'author': json['author'],
        'text': json['text'],
    };
}

export function VideoVideoIdGet200ResponseCommentsInnerToJSON(json: any): VideoVideoIdGet200ResponseCommentsInner {
    return VideoVideoIdGet200ResponseCommentsInnerToJSONTyped(json, false);
}

export function VideoVideoIdGet200ResponseCommentsInnerToJSONTyped(value?: VideoVideoIdGet200ResponseCommentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'author': value['author'],
        'text': value['text'],
    };
}

