/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdSubscribePost200Response
 */
export interface VideoVideoIdSubscribePost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof VideoVideoIdSubscribePost200Response
     */
    subscriptionStatus: boolean;
}

/**
 * Check if a given object implements the VideoVideoIdSubscribePost200Response interface.
 */
export function instanceOfVideoVideoIdSubscribePost200Response(value: object): value is VideoVideoIdSubscribePost200Response {
    if (!('subscriptionStatus' in value) || value['subscriptionStatus'] === undefined) return false;
    return true;
}

export function VideoVideoIdSubscribePost200ResponseFromJSON(json: any): VideoVideoIdSubscribePost200Response {
    return VideoVideoIdSubscribePost200ResponseFromJSONTyped(json, false);
}

export function VideoVideoIdSubscribePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdSubscribePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionStatus': json['subscriptionStatus'],
    };
}

export function VideoVideoIdSubscribePost200ResponseToJSON(json: any): VideoVideoIdSubscribePost200Response {
    return VideoVideoIdSubscribePost200ResponseToJSONTyped(json, false);
}

export function VideoVideoIdSubscribePost200ResponseToJSONTyped(value?: VideoVideoIdSubscribePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionStatus': value['subscriptionStatus'],
    };
}

