/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdGet200ResponseCommentsInnerUser
 */
export interface VideoVideoIdGet200ResponseCommentsInnerUser {
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdGet200ResponseCommentsInnerUser
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdGet200ResponseCommentsInnerUser
     */
    profilePictureUrl: string | null;
}

/**
 * Check if a given object implements the VideoVideoIdGet200ResponseCommentsInnerUser interface.
 */
export function instanceOfVideoVideoIdGet200ResponseCommentsInnerUser(value: object): value is VideoVideoIdGet200ResponseCommentsInnerUser {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('profilePictureUrl' in value) || value['profilePictureUrl'] === undefined) return false;
    return true;
}

export function VideoVideoIdGet200ResponseCommentsInnerUserFromJSON(json: any): VideoVideoIdGet200ResponseCommentsInnerUser {
    return VideoVideoIdGet200ResponseCommentsInnerUserFromJSONTyped(json, false);
}

export function VideoVideoIdGet200ResponseCommentsInnerUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdGet200ResponseCommentsInnerUser {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'profilePictureUrl': json['profilePictureUrl'],
    };
}

export function VideoVideoIdGet200ResponseCommentsInnerUserToJSON(json: any): VideoVideoIdGet200ResponseCommentsInnerUser {
    return VideoVideoIdGet200ResponseCommentsInnerUserToJSONTyped(json, false);
}

export function VideoVideoIdGet200ResponseCommentsInnerUserToJSONTyped(value?: VideoVideoIdGet200ResponseCommentsInnerUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'profilePictureUrl': value['profilePictureUrl'],
    };
}

