/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoVideoIdCommentsGet200ResponseCommentsInnerUser } from './VideoVideoIdCommentsGet200ResponseCommentsInnerUser';
import {
    VideoVideoIdCommentsGet200ResponseCommentsInnerUserFromJSON,
    VideoVideoIdCommentsGet200ResponseCommentsInnerUserFromJSONTyped,
    VideoVideoIdCommentsGet200ResponseCommentsInnerUserToJSON,
    VideoVideoIdCommentsGet200ResponseCommentsInnerUserToJSONTyped,
} from './VideoVideoIdCommentsGet200ResponseCommentsInnerUser';

/**
 * 
 * @export
 * @interface VideoVideoIdCommentsGet200ResponseCommentsInner
 */
export interface VideoVideoIdCommentsGet200ResponseCommentsInner {
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdCommentsGet200ResponseCommentsInner
     */
    id: string;
    /**
     * 
     * @type {VideoVideoIdCommentsGet200ResponseCommentsInnerUser}
     * @memberof VideoVideoIdCommentsGet200ResponseCommentsInner
     */
    user: VideoVideoIdCommentsGet200ResponseCommentsInnerUser;
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdCommentsGet200ResponseCommentsInner
     */
    text: string;
    /**
     * 
     * @type {Date}
     * @memberof VideoVideoIdCommentsGet200ResponseCommentsInner
     */
    timeStamp: Date;
}

/**
 * Check if a given object implements the VideoVideoIdCommentsGet200ResponseCommentsInner interface.
 */
export function instanceOfVideoVideoIdCommentsGet200ResponseCommentsInner(value: object): value is VideoVideoIdCommentsGet200ResponseCommentsInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('timeStamp' in value) || value['timeStamp'] === undefined) return false;
    return true;
}

export function VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSON(json: any): VideoVideoIdCommentsGet200ResponseCommentsInner {
    return VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSONTyped(json, false);
}

export function VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdCommentsGet200ResponseCommentsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'user': VideoVideoIdCommentsGet200ResponseCommentsInnerUserFromJSON(json['user']),
        'text': json['text'],
        'timeStamp': (new Date(json['timeStamp'])),
    };
}

export function VideoVideoIdCommentsGet200ResponseCommentsInnerToJSON(json: any): VideoVideoIdCommentsGet200ResponseCommentsInner {
    return VideoVideoIdCommentsGet200ResponseCommentsInnerToJSONTyped(json, false);
}

export function VideoVideoIdCommentsGet200ResponseCommentsInnerToJSONTyped(value?: VideoVideoIdCommentsGet200ResponseCommentsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user': VideoVideoIdCommentsGet200ResponseCommentsInnerUserToJSON(value['user']),
        'text': value['text'],
        'timeStamp': ((value['timeStamp']).toISOString()),
    };
}

