/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdLikePostRequest
 */
export interface VideoVideoIdLikePostRequest {
    /**
     * 
     * @type {boolean}
     * @memberof VideoVideoIdLikePostRequest
     */
    isLiking: boolean;
}

/**
 * Check if a given object implements the VideoVideoIdLikePostRequest interface.
 */
export function instanceOfVideoVideoIdLikePostRequest(value: object): value is VideoVideoIdLikePostRequest {
    if (!('isLiking' in value) || value['isLiking'] === undefined) return false;
    return true;
}

export function VideoVideoIdLikePostRequestFromJSON(json: any): VideoVideoIdLikePostRequest {
    return VideoVideoIdLikePostRequestFromJSONTyped(json, false);
}

export function VideoVideoIdLikePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdLikePostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'isLiking': json['isLiking'],
    };
}

export function VideoVideoIdLikePostRequestToJSON(json: any): VideoVideoIdLikePostRequest {
    return VideoVideoIdLikePostRequestToJSONTyped(json, false);
}

export function VideoVideoIdLikePostRequestToJSONTyped(value?: VideoVideoIdLikePostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isLiking': value['isLiking'],
    };
}

