/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoVideoIdCommentPostRequest
 */
export interface VideoVideoIdCommentPostRequest {
    /**
     * 
     * @type {string}
     * @memberof VideoVideoIdCommentPostRequest
     */
    comment: string;
}

/**
 * Check if a given object implements the VideoVideoIdCommentPostRequest interface.
 */
export function instanceOfVideoVideoIdCommentPostRequest(value: object): value is VideoVideoIdCommentPostRequest {
    if (!('comment' in value) || value['comment'] === undefined) return false;
    return true;
}

export function VideoVideoIdCommentPostRequestFromJSON(json: any): VideoVideoIdCommentPostRequest {
    return VideoVideoIdCommentPostRequestFromJSONTyped(json, false);
}

export function VideoVideoIdCommentPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdCommentPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'],
    };
}

export function VideoVideoIdCommentPostRequestToJSON(json: any): VideoVideoIdCommentPostRequest {
    return VideoVideoIdCommentPostRequestToJSONTyped(json, false);
}

export function VideoVideoIdCommentPostRequestToJSONTyped(value?: VideoVideoIdCommentPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comment': value['comment'],
    };
}

