/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VideoVideoIdCommentsGet200ResponseCommentsInner } from './VideoVideoIdCommentsGet200ResponseCommentsInner';
import {
    VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSON,
    VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSONTyped,
    VideoVideoIdCommentsGet200ResponseCommentsInnerToJSON,
    VideoVideoIdCommentsGet200ResponseCommentsInnerToJSONTyped,
} from './VideoVideoIdCommentsGet200ResponseCommentsInner';

/**
 * 
 * @export
 * @interface VideoVideoIdCommentsGet200Response
 */
export interface VideoVideoIdCommentsGet200Response {
    /**
     * 
     * @type {Array<VideoVideoIdCommentsGet200ResponseCommentsInner>}
     * @memberof VideoVideoIdCommentsGet200Response
     */
    comments: Array<VideoVideoIdCommentsGet200ResponseCommentsInner>;
}

/**
 * Check if a given object implements the VideoVideoIdCommentsGet200Response interface.
 */
export function instanceOfVideoVideoIdCommentsGet200Response(value: object): value is VideoVideoIdCommentsGet200Response {
    if (!('comments' in value) || value['comments'] === undefined) return false;
    return true;
}

export function VideoVideoIdCommentsGet200ResponseFromJSON(json: any): VideoVideoIdCommentsGet200Response {
    return VideoVideoIdCommentsGet200ResponseFromJSONTyped(json, false);
}

export function VideoVideoIdCommentsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoVideoIdCommentsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'comments': ((json['comments'] as Array<any>).map(VideoVideoIdCommentsGet200ResponseCommentsInnerFromJSON)),
    };
}

export function VideoVideoIdCommentsGet200ResponseToJSON(json: any): VideoVideoIdCommentsGet200Response {
    return VideoVideoIdCommentsGet200ResponseToJSONTyped(json, false);
}

export function VideoVideoIdCommentsGet200ResponseToJSONTyped(value?: VideoVideoIdCommentsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'comments': ((value['comments'] as Array<any>).map(VideoVideoIdCommentsGet200ResponseCommentsInnerToJSON)),
    };
}

