FROM node:23-slim

RUN apt-get update -y
RUN apt-get install -y openssl
RUN apt-get clean 
RUN rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY ./node-fastify-webapi-sample /app

RUN npm install
RUN npm run build

CMD ["node","dist/index.js"]