services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default AMQP port
      - "15672:15672" # RabbitMQ management port
    volumes:
      - ./src/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_LOAD_DEFINITIONS: "true"
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","ping"]
      interval: 2s
      retries: 10
      timeout: 5s
  
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./src/minio/data:/data
      - ./src/minio/buckets:/buckets
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}); do
        sleep 3;
      done;
      mc mb myminio/video;
      mc mb myminio/video-encoded;
      "
  
  transcoder:
    build: src/transcoder
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

    environment:
      RABBITMQ_HOST: rabbitmq
      QUEUE_NAME : video.transcode
      S3_BUCKET_NAME: video
      S3_BUCKET_ENCODED_NAME: video-encoded
      STATUS_QUEUE_NAME: video.status
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}

  controller:
    build: src/controller
    ports:
     - "3000:3000"
    environment:
      S3_REGION: eu-west-1
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: ${MINIO_ROOT_USER}
      S3_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
      - rabbitmq