services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ default AMQP port
      - "15672:15672" # RabbitMQ management port
    volumes:
      - ./src/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./src/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      RABBITMQ_LOAD_DEFINITIONS: "true"
      RABBITMQ_DEFINITIONS_FILE: "/etc/rabbitmq/definitions.json"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics","ping"]
      interval: 2s
      retries: 10
      timeout: 5s
  
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
      - minio-buckets:/buckets
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (mc alias set myminio http://minio:9000 ${S3_ACCESS_KEY} ${S3_SECRET_KEY}); do
        sleep 3;
      done;
      mc mb myminio/video;
      mc anonymous set public myminio/video
      "
  
  transcoder:
    build: src/transcoder
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      TRANSCODE_QUEUE_NAME : ${TRANSCODE_QUEUE_NAME}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_BUCKET_ENCODED_NAME: ${S3_BUCKET_ENCODED_NAME}
      STATUS_QUEUE_NAME: ${STATUS_QUEUE_NAME}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      
  controller:
    build: src/controller
    ports:
     - "3000:3000"
    environment:
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      RABBITMQ_AMQP: ${RABBITMQ_AMQP}
      TRANSCODE_QUEUE_NAME: ${TRANSCODE_QUEUE_NAME}
      STATUS_QUEUE_NAME: ${STATUS_QUEUE_NAME}
      DB_CONNECTION: ${DB_CONNECTION}
    depends_on:
      - minio
      - rabbitmq

  nginx:
    image: nginx
    ports:
      - "9005:9000"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  minio-data:
  minio-buckets: