# Base image
FROM ubuntu:22.04

# Copy requirements.txt to the container
COPY ./requirements.txt ./requirements.txt

# Install dependencies and configure the container
RUN apt-get update && \
    apt-get install -y git python3-pip openssh-server && \
    pip3 install -r ./requirements.txt && \
    mkdir /var/run/sshd && \
    echo "root:DockerSSH" | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose the SSH port
EXPOSE 22

# Start the SSH server
CMD ["/usr/sbin/sshd", "-D"]
