/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLoginPost200Response,
  AuthLoginPost500Response,
  AuthLoginPostRequest,
  AuthSignupPostRequest,
  Get200Response,
} from '../models/index';
import {
    AuthLoginPost200ResponseFromJSON,
    AuthLoginPost200ResponseToJSON,
    AuthLoginPost500ResponseFromJSON,
    AuthLoginPost500ResponseToJSON,
    AuthLoginPostRequestFromJSON,
    AuthLoginPostRequestToJSON,
    AuthSignupPostRequestFromJSON,
    AuthSignupPostRequestToJSON,
    Get200ResponseFromJSON,
    Get200ResponseToJSON,
} from '../models/index';

export interface AuthGithubCallbackGetRequest {
    code: string;
}

export interface AuthLoginPostOperationRequest {
    authLoginPostRequest: AuthLoginPostRequest;
}

export interface AuthSignupPostOperationRequest {
    authSignupPostRequest: AuthSignupPostRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * GitHub OAuth callback endpoint
     * Process GitHub authentication callback
     */
    async authGithubCallbackGetRaw(requestParameters: AuthGithubCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authGithubCallbackGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/github/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * GitHub OAuth callback endpoint
     * Process GitHub authentication callback
     */
    async authGithubCallbackGet(requestParameters: AuthGithubCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authGithubCallbackGetRaw(requestParameters, initOverrides);
    }

    /**
     * Initiate authentication with GitHub
     * GitHub authentication
     */
    async authGithubGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/github`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiate authentication with GitHub
     * GitHub authentication
     */
    async authGithubGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authGithubGetRaw(initOverrides);
    }

    /**
     * Github login
     * Github endpoint
     */
    async authGithubLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/github/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Github login
     * Github endpoint
     */
    async authGithubLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginPost200Response> {
        const response = await this.authGithubLoginGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * User login
     * Login endpoint
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
        if (requestParameters['authLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authLoginPostRequest',
                'Required parameter "authLoginPostRequest" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLoginPostRequestToJSON(requestParameters['authLoginPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * User login
     * Login endpoint
     */
    async authLoginPost(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginPost200Response> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Protected endpoint
     * Protected endpoint requiring JWT
     */
    async authProtectedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Get200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/protected`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Get200ResponseFromJSON(jsonValue));
    }

    /**
     * Protected endpoint
     * Protected endpoint requiring JWT
     */
    async authProtectedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Get200Response> {
        const response = await this.authProtectedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * User sign up
     * Sign up endpoint
     */
    async authSignupPostRaw(requestParameters: AuthSignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['authSignupPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authSignupPostRequest',
                'Required parameter "authSignupPostRequest" was null or undefined when calling authSignupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSignupPostRequestToJSON(requestParameters['authSignupPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * User sign up
     * Sign up endpoint
     */
    async authSignupPost(requestParameters: AuthSignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.authSignupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
