/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLoginPost200Response,
  AuthLoginPost500Response,
  AuthLoginPostRequest,
  AuthSignupPost200Response,
  AuthSignupPost500Response,
  AuthSignupPostRequest,
  Get200Response,
} from '../models/index';
import {
    AuthLoginPost200ResponseFromJSON,
    AuthLoginPost200ResponseToJSON,
    AuthLoginPost500ResponseFromJSON,
    AuthLoginPost500ResponseToJSON,
    AuthLoginPostRequestFromJSON,
    AuthLoginPostRequestToJSON,
    AuthSignupPost200ResponseFromJSON,
    AuthSignupPost200ResponseToJSON,
    AuthSignupPost500ResponseFromJSON,
    AuthSignupPost500ResponseToJSON,
    AuthSignupPostRequestFromJSON,
    AuthSignupPostRequestToJSON,
    Get200ResponseFromJSON,
    Get200ResponseToJSON,
} from '../models/index';

export interface AuthLoginPostOperationRequest {
    authLoginPostRequest: AuthLoginPostRequest;
}

export interface AuthSignupPostOperationRequest {
    authSignupPostRequest: AuthSignupPostRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * User login
     * Login endpoint
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLoginPost200Response>> {
        if (requestParameters['authLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authLoginPostRequest',
                'Required parameter "authLoginPostRequest" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthLoginPostRequestToJSON(requestParameters['authLoginPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthLoginPost200ResponseFromJSON(jsonValue));
    }

    /**
     * User login
     * Login endpoint
     */
    async authLoginPost(requestParameters: AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLoginPost200Response> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Protected endpoint
     * Protected endpoint requiring JWT
     */
    async authProtectedGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Get200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/auth/protected`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Get200ResponseFromJSON(jsonValue));
    }

    /**
     * Protected endpoint
     * Protected endpoint requiring JWT
     */
    async authProtectedGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Get200Response> {
        const response = await this.authProtectedGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * User sign up
     * Sign up endpoint
     */
    async authSignupPostRaw(requestParameters: AuthSignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthSignupPost200Response>> {
        if (requestParameters['authSignupPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authSignupPostRequest',
                'Required parameter "authSignupPostRequest" was null or undefined when calling authSignupPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/signup`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthSignupPostRequestToJSON(requestParameters['authSignupPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthSignupPost200ResponseFromJSON(jsonValue));
    }

    /**
     * User sign up
     * Sign up endpoint
     */
    async authSignupPost(requestParameters: AuthSignupPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthSignupPost200Response> {
        const response = await this.authSignupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
