/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLoginPost500Response,
  VideoAllVideosGet200ResponseInner,
  VideoVideoIdCommentPostRequest,
  VideoVideoIdCommentsGet200Response,
  VideoVideoIdGet200Response,
  VideoVideoIdLikePost200Response,
  VideoVideoIdLikePostRequest,
  VideoVideoIdSubscribePost200Response,
  VideoVideoIdSubscribePostRequest,
} from '../models/index';
import {
    AuthLoginPost500ResponseFromJSON,
    AuthLoginPost500ResponseToJSON,
    VideoAllVideosGet200ResponseInnerFromJSON,
    VideoAllVideosGet200ResponseInnerToJSON,
    VideoVideoIdCommentPostRequestFromJSON,
    VideoVideoIdCommentPostRequestToJSON,
    VideoVideoIdCommentsGet200ResponseFromJSON,
    VideoVideoIdCommentsGet200ResponseToJSON,
    VideoVideoIdGet200ResponseFromJSON,
    VideoVideoIdGet200ResponseToJSON,
    VideoVideoIdLikePost200ResponseFromJSON,
    VideoVideoIdLikePost200ResponseToJSON,
    VideoVideoIdLikePostRequestFromJSON,
    VideoVideoIdLikePostRequestToJSON,
    VideoVideoIdSubscribePost200ResponseFromJSON,
    VideoVideoIdSubscribePost200ResponseToJSON,
    VideoVideoIdSubscribePostRequestFromJSON,
    VideoVideoIdSubscribePostRequestToJSON,
} from '../models/index';

export interface VideoAllVideosGetRequest {
    skip: number;
    take: number;
}

export interface VideoSearchPostRequest {
    q: string;
}

export interface VideoSubscriptionsSubscriberIdGetRequest {
    skip: number;
    take: number;
    subscriberId: string;
}

export interface VideoUserUserIdVideosGetRequest {
    userId: string;
}

export interface VideoVideoIdCommentPostOperationRequest {
    videoId: string;
    videoVideoIdCommentPostRequest: VideoVideoIdCommentPostRequest;
}

export interface VideoVideoIdCommentsGetRequest {
    skip: number;
    take: number;
    videoId: string;
}

export interface VideoVideoIdGetRequest {
    videoId: string;
}

export interface VideoVideoIdIsSubscribedGetRequest {
    videoId: string;
}

export interface VideoVideoIdLikePostOperationRequest {
    videoId: string;
    videoVideoIdLikePostRequest: VideoVideoIdLikePostRequest;
}

export interface VideoVideoIdSubscribePostOperationRequest {
    videoId: string;
    videoVideoIdSubscribePostRequest: VideoVideoIdSubscribePostRequest;
}

/**
 * 
 */
export class VideoApi extends runtime.BaseAPI {

    /**
     */
    async videoAllVideosGetRaw(requestParameters: VideoAllVideosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VideoAllVideosGet200ResponseInner>>> {
        if (requestParameters['skip'] == null) {
            throw new runtime.RequiredError(
                'skip',
                'Required parameter "skip" was null or undefined when calling videoAllVideosGet().'
            );
        }

        if (requestParameters['take'] == null) {
            throw new runtime.RequiredError(
                'take',
                'Required parameter "take" was null or undefined when calling videoAllVideosGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/all-videos`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VideoAllVideosGet200ResponseInnerFromJSON));
    }

    /**
     */
    async videoAllVideosGet(requestParameters: VideoAllVideosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VideoAllVideosGet200ResponseInner>> {
        const response = await this.videoAllVideosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoSearchPostRaw(requestParameters: VideoSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VideoAllVideosGet200ResponseInner>>> {
        if (requestParameters['q'] == null) {
            throw new runtime.RequiredError(
                'q',
                'Required parameter "q" was null or undefined when calling videoSearchPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/search`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VideoAllVideosGet200ResponseInnerFromJSON));
    }

    /**
     */
    async videoSearchPost(requestParameters: VideoSearchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VideoAllVideosGet200ResponseInner>> {
        const response = await this.videoSearchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoSubscriptionsSubscriberIdGetRaw(requestParameters: VideoSubscriptionsSubscriberIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VideoAllVideosGet200ResponseInner>>> {
        if (requestParameters['skip'] == null) {
            throw new runtime.RequiredError(
                'skip',
                'Required parameter "skip" was null or undefined when calling videoSubscriptionsSubscriberIdGet().'
            );
        }

        if (requestParameters['take'] == null) {
            throw new runtime.RequiredError(
                'take',
                'Required parameter "take" was null or undefined when calling videoSubscriptionsSubscriberIdGet().'
            );
        }

        if (requestParameters['subscriberId'] == null) {
            throw new runtime.RequiredError(
                'subscriberId',
                'Required parameter "subscriberId" was null or undefined when calling videoSubscriptionsSubscriberIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/subscriptions/{subscriberId}`.replace(`{${"subscriberId"}}`, encodeURIComponent(String(requestParameters['subscriberId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VideoAllVideosGet200ResponseInnerFromJSON));
    }

    /**
     */
    async videoSubscriptionsSubscriberIdGet(requestParameters: VideoSubscriptionsSubscriberIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VideoAllVideosGet200ResponseInner>> {
        const response = await this.videoSubscriptionsSubscriberIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoUserUserIdVideosGetRaw(requestParameters: VideoUserUserIdVideosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<VideoAllVideosGet200ResponseInner>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling videoUserUserIdVideosGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/user/{userId}/videos`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VideoAllVideosGet200ResponseInnerFromJSON));
    }

    /**
     */
    async videoUserUserIdVideosGet(requestParameters: VideoUserUserIdVideosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<VideoAllVideosGet200ResponseInner>> {
        const response = await this.videoUserUserIdVideosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdCommentPostRaw(requestParameters: VideoVideoIdCommentPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdCommentPost().'
            );
        }

        if (requestParameters['videoVideoIdCommentPostRequest'] == null) {
            throw new runtime.RequiredError(
                'videoVideoIdCommentPostRequest',
                'Required parameter "videoVideoIdCommentPostRequest" was null or undefined when calling videoVideoIdCommentPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}/comment`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoVideoIdCommentPostRequestToJSON(requestParameters['videoVideoIdCommentPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async videoVideoIdCommentPost(requestParameters: VideoVideoIdCommentPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.videoVideoIdCommentPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdCommentsGetRaw(requestParameters: VideoVideoIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoVideoIdCommentsGet200Response>> {
        if (requestParameters['skip'] == null) {
            throw new runtime.RequiredError(
                'skip',
                'Required parameter "skip" was null or undefined when calling videoVideoIdCommentsGet().'
            );
        }

        if (requestParameters['take'] == null) {
            throw new runtime.RequiredError(
                'take',
                'Required parameter "take" was null or undefined when calling videoVideoIdCommentsGet().'
            );
        }

        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdCommentsGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['skip'] != null) {
            queryParameters['skip'] = requestParameters['skip'];
        }

        if (requestParameters['take'] != null) {
            queryParameters['take'] = requestParameters['take'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}/comments`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoVideoIdCommentsGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async videoVideoIdCommentsGet(requestParameters: VideoVideoIdCommentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoVideoIdCommentsGet200Response> {
        const response = await this.videoVideoIdCommentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdGetRaw(requestParameters: VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoVideoIdGet200Response>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoVideoIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async videoVideoIdGet(requestParameters: VideoVideoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoVideoIdGet200Response> {
        const response = await this.videoVideoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdIsSubscribedGetRaw(requestParameters: VideoVideoIdIsSubscribedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoVideoIdSubscribePost200Response>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdIsSubscribedGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}/is-subscribed`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoVideoIdSubscribePost200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async videoVideoIdIsSubscribedGet(requestParameters: VideoVideoIdIsSubscribedGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoVideoIdSubscribePost200Response> {
        const response = await this.videoVideoIdIsSubscribedGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdLikePostRaw(requestParameters: VideoVideoIdLikePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoVideoIdLikePost200Response>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdLikePost().'
            );
        }

        if (requestParameters['videoVideoIdLikePostRequest'] == null) {
            throw new runtime.RequiredError(
                'videoVideoIdLikePostRequest',
                'Required parameter "videoVideoIdLikePostRequest" was null or undefined when calling videoVideoIdLikePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}/like`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoVideoIdLikePostRequestToJSON(requestParameters['videoVideoIdLikePostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoVideoIdLikePost200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async videoVideoIdLikePost(requestParameters: VideoVideoIdLikePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoVideoIdLikePost200Response> {
        const response = await this.videoVideoIdLikePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async videoVideoIdSubscribePostRaw(requestParameters: VideoVideoIdSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VideoVideoIdSubscribePost200Response>> {
        if (requestParameters['videoId'] == null) {
            throw new runtime.RequiredError(
                'videoId',
                'Required parameter "videoId" was null or undefined when calling videoVideoIdSubscribePost().'
            );
        }

        if (requestParameters['videoVideoIdSubscribePostRequest'] == null) {
            throw new runtime.RequiredError(
                'videoVideoIdSubscribePostRequest',
                'Required parameter "videoVideoIdSubscribePostRequest" was null or undefined when calling videoVideoIdSubscribePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/video/{videoId}/subscribe`.replace(`{${"videoId"}}`, encodeURIComponent(String(requestParameters['videoId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VideoVideoIdSubscribePostRequestToJSON(requestParameters['videoVideoIdSubscribePostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VideoVideoIdSubscribePost200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async videoVideoIdSubscribePost(requestParameters: VideoVideoIdSubscribePostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VideoVideoIdSubscribePost200Response> {
        const response = await this.videoVideoIdSubscribePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
