/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthLoginPost500Response
 */
export interface AuthLoginPost500Response {
    /**
     * 
     * @type {string}
     * @memberof AuthLoginPost500Response
     */
    error: string;
}

/**
 * Check if a given object implements the AuthLoginPost500Response interface.
 */
export function instanceOfAuthLoginPost500Response(value: object): value is AuthLoginPost500Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function AuthLoginPost500ResponseFromJSON(json: any): AuthLoginPost500Response {
    return AuthLoginPost500ResponseFromJSONTyped(json, false);
}

export function AuthLoginPost500ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthLoginPost500Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function AuthLoginPost500ResponseToJSON(json: any): AuthLoginPost500Response {
    return AuthLoginPost500ResponseToJSONTyped(json, false);
}

export function AuthLoginPost500ResponseToJSONTyped(value?: AuthLoginPost500Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

