/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthUserUserIdPutRequest
 */
export interface AuthUserUserIdPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthUserUserIdPutRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserUserIdPutRequest
     */
    password?: string;
}

/**
 * Check if a given object implements the AuthUserUserIdPutRequest interface.
 */
export function instanceOfAuthUserUserIdPutRequest(value: object): value is AuthUserUserIdPutRequest {
    return true;
}

export function AuthUserUserIdPutRequestFromJSON(json: any): AuthUserUserIdPutRequest {
    return AuthUserUserIdPutRequestFromJSONTyped(json, false);
}

export function AuthUserUserIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserUserIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function AuthUserUserIdPutRequestToJSON(json: any): AuthUserUserIdPutRequest {
    return AuthUserUserIdPutRequestToJSONTyped(json, false);
}

export function AuthUserUserIdPutRequestToJSONTyped(value?: AuthUserUserIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'password': value['password'],
    };
}

