/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoUploadUrlGet200Response
 */
export interface VideoUploadUrlGet200Response {
    /**
     * 
     * @type {string}
     * @memberof VideoUploadUrlGet200Response
     */
    url: string;
}

/**
 * Check if a given object implements the VideoUploadUrlGet200Response interface.
 */
export function instanceOfVideoUploadUrlGet200Response(value: object): value is VideoUploadUrlGet200Response {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function VideoUploadUrlGet200ResponseFromJSON(json: any): VideoUploadUrlGet200Response {
    return VideoUploadUrlGet200ResponseFromJSONTyped(json, false);
}

export function VideoUploadUrlGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoUploadUrlGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function VideoUploadUrlGet200ResponseToJSON(json: any): VideoUploadUrlGet200Response {
    return VideoUploadUrlGet200ResponseToJSONTyped(json, false);
}

export function VideoUploadUrlGet200ResponseToJSONTyped(value?: VideoUploadUrlGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

