/* tslint:disable */
/* eslint-disable */
/**
 * Test swagger
 * Testing the Fastify swagger API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VideoTranscodeVideoPostRequest
 */
export interface VideoTranscodeVideoPostRequest {
    /**
     * 
     * @type {string}
     * @memberof VideoTranscodeVideoPostRequest
     */
    videoID: string;
}

/**
 * Check if a given object implements the VideoTranscodeVideoPostRequest interface.
 */
export function instanceOfVideoTranscodeVideoPostRequest(value: object): value is VideoTranscodeVideoPostRequest {
    if (!('videoID' in value) || value['videoID'] === undefined) return false;
    return true;
}

export function VideoTranscodeVideoPostRequestFromJSON(json: any): VideoTranscodeVideoPostRequest {
    return VideoTranscodeVideoPostRequestFromJSONTyped(json, false);
}

export function VideoTranscodeVideoPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VideoTranscodeVideoPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'videoID': json['videoID'],
    };
}

export function VideoTranscodeVideoPostRequestToJSON(json: any): VideoTranscodeVideoPostRequest {
    return VideoTranscodeVideoPostRequestToJSONTyped(json, false);
}

export function VideoTranscodeVideoPostRequestToJSONTyped(value?: VideoTranscodeVideoPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'videoID': value['videoID'],
    };
}

